spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BeginRestful;encrypt=true;trustServerCertificate=true
    username: sa
    password: 170903
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
jwt:
  signer-key: HJ4ppveef04BKJzTq+dyLhRdicqYiQWxaSqTLiTUxksDu4zMs/NLfrJsbHz+4OiB